# Generated by Django 4.0.3 on 2022-03-12 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itm', '0003_inproduct_instorageperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inproduct',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 0, 20, 16, 924170)),
        ),
        migrations.AlterField(
            model_name='inproduct',
            name='instorageperson',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inproduct',
            name='takeinstorageperson',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='getinstorageperson',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='out_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 0, 20, 16, 925166)),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='outstorageperson',
            field=models.CharField(max_length=200),
        ),
    ]
