# Generated by Django 4.0.3 on 2022-03-12 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itm', '0004_alter_inproduct_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outproduct',
            name='receiver_name',
        ),
        migrations.AlterField(
            model_name='inproduct',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 2, 27, 3, 608618)),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='out_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 2, 27, 3, 608618)),
        ),
    ]
