# Generated by Django 4.0.3 on 2022-03-05 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('inload_number', models.CharField(max_length=200)),
                ('count', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('tonna', 'tonna'), ('gramm', 'gramm'), ('litr', 'litr'), ('metr', 'metr'), ('santimetr', 'sm')], max_length=30)),
                ('in_date', models.DateTimeField(default=datetime.datetime(2022, 3, 5, 21, 54, 49, 177429))),
            ],
            options={
                'db_table': 'Inproduct',
            },
        ),
        migrations.CreateModel(
            name='Outproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('receiver_name', models.CharField(max_length=200)),
                ('outload_number', models.CharField(max_length=200)),
                ('count', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('tonna', 'tonna'), ('gramm', 'gramm'), ('litr', 'litr'), ('metr', 'metr'), ('santimetr', 'sm')], max_length=30)),
                ('out_date', models.DateTimeField(default=datetime.datetime(2022, 3, 5, 21, 54, 49, 177429))),
            ],
            options={
                'db_table': 'Outproduct',
            },
        ),
    ]
