# Generated by Django 4.0.3 on 2022-03-06 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('count', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('tonna', 'tonna'), ('gramm', 'gramm'), ('litr', 'litr'), ('metr', 'metr'), ('santimetr', 'sm'), ('dona', 'dona')], max_length=30)),
            ],
            options={
                'db_table': 'BalanceStorage',
            },
        ),
        migrations.AlterField(
            model_name='inproduct',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 22, 41, 31, 368409)),
        ),
        migrations.AlterField(
            model_name='inproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('tonna', 'tonna'), ('gramm', 'gramm'), ('litr', 'litr'), ('metr', 'metr'), ('santimetr', 'sm'), ('dona', 'dona')], max_length=30),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='out_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 22, 41, 31, 368409)),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('tonna', 'tonna'), ('gramm', 'gramm'), ('litr', 'litr'), ('metr', 'metr'), ('santimetr', 'sm'), ('dona', 'dona')], max_length=30),
        ),
    ]
